export const languages = {
  en: {
    editions: 'Editions',
    controller: 'Controller',
    about: 'About',
    explore: 'Explore',
    news: 'News',
    faq: 'Faq',
    currentLang: 'English',
    release: 'Release:',
    buy: 'buy now',
    buyGame: 'buy',
    headerSubtitle:
      'Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten city.',
    editionsItem: 'Standard Editions ',
    editionsdescriptionPs5Offline: ' Offline play enabled',
    editionsdescriptionPs5Remote: ' Remote Play supported',
    editionsdescriptionPs5Trigger: 'Trigger effect required',
    editionsdescriptionFeatures: 'All features of Standard Edition',
    editionsdescriptionDragon: 'Dragon backpack',
    editionsdescriptionSoundtrack: 'Official digital soundtrack',
    сontrollerTiltle: 'DualSense',
    descController1:
      'You can also buy an exclusive controller for PS5 with the game <span>Stray</span>',
    descController2:
      'If you purchase a controller and a game (any edition), you will receive a <span>15%</span> discount on two items.',
    about: 'About Game',
    aboutTitle: 'Watch the Trailer',
    exploreTitle: '  Explore <span>Stray</span> series',
    requirementsPc: 'Here are (PC) System Requirements',
    minimumPc: 'Minimum',
    recommendedPc: 'Recommended',
    PStitle: '<span>Stray</span> для PS4',
    PsRequirementStandard: 'Standard',
    PsRequirementLimited: 'Limited',
    news: 'News',
    newsTitle1: 'Review Roundup',
    newsTitle2: 'Cyberpunk Cat',
    newsTitle3: 'Stray Is A Big Hit!',
    newsSubTitle1:
      'Stray is the tale of a small cat who falls into a subterranean city inhabited entirely by robots. The titular stray will befriend a drone, explore<p class="text-overflow"> small hub worlds, and solve puzzles with their feline brain as it seeks to make its way back home</p><a class="dots">...</a>',
    newsSubTitle2: ` Will Be Free Through PlayStation Plus' Higher Tiers. Stray, the highly-anticipated cyberpunk adventure game in which players<p class="text-overflow"> take on the role of backpack-wearing cat working its way through a robot-infested city, now has a release date. Originally slated for release in "early 2022,"</p><a class="dots">...</a>`,
    newsSubTitle3: ` Stray has officially arrived today, giving fans an opportunity to play as a digital version<p class="text-overflow"> of nature's perfect purring machine. As the titular stray cat lost in a strange city inhabited by robots, it'll be up to you to help the feline find its way home and avoid crossing paths with merciless androids</p><a class="dots">...</a>`,
    question1: 'When is the release??',
    question2: 'The game give the opportunity only to play as a little cat?',
    question3: 'What is <span class="stray"> Stray </span> about?',
    answer1: `The Game's Release spending in в July 19`,
    answer2: `Yeah, just for him.`,
    answer3:
      'The story follows a stray cat who falls into a walled city populated by robots, machines, and mutant bacteria, and sets out to return to the surface with the help of a drone companion, B-12.The game is presented through a third-person perspective. ',
    footerInfo:
      'Download of this product is subject to the PlayStation Network Terms of Service and our Software Usage Terms plus any specific additional conditions applying to this product. If you do not wish to accept these terms, do not download this product. See Terms of Service for more important information.',
  },
  ru: {
    editions: 'Издания',
    controller: 'Джостик',
    about: 'Об игре',
    explore: 'Исследовать',
    news: 'Новости',
    faq: 'Помощь',
    currentLang: 'Русский',
    release: 'Релиз:',
    buy: 'Купить Сейчас',
    buyGame: 'купить',
    headerSubtitle:
      'Потерянный, одинокий и оторванный от семьи, бродячий кот должен распутать древнюю тайну, чтобы спастись из давно забытого города.',
    editionsItem: 'Стандартные издания ',
    editionsItemDeluxe: 'Эксклюзивные издания ',
    editionsdescriptionPs5Offline: 'Оффлайн режим',
    editionsdescriptionPs5Remote: 'Удаленное воспроизведение',
    editionsdescriptionPs5Trigger: 'Требуется триггерный эффект',
    editionsdescriptionFeatures: 'Все фишки стандартного издания',
    editionsdescriptionDragon: 'Рюкзак дракона',
    editionsdescriptionSoundtrack: 'Официальный саундтрек',
    сontrollerTiltle: 'Контроллер',
    descController1:
      'Вы также можете купить эксклюзвный контроллер для PS5 вместе с игрой<span>Stray</span>',
    descController2:
      'Если вы покупаете контроллер и игру (в любом издании) вы так получаете <span>15%</span> скидку на две дополнительной продукции',
    about: 'Об Игре',
    aboutTitle: 'Смотреть Трейлер',
    exploreTitle: '  Исследуй <span>Stray</span> ',
    requirementsPc: 'Системные требования для PC',
    minimumPc: 'Минимальные',
    recommendedPc: 'Рекомендуемые',
    PStitle: '<span>Stray</span> для PS4',
    PsRequirementStandard: 'Стандартные',
    PsRequirementLimited: 'Ограниченные',
    news: 'Новости',
    newsTitle1: 'Обзорная информация',
    newsTitle2: 'Киберпанк мира кошек',
    newsTitle3: 'Stray несомненно хит!',
    newsSubTitle1:
      'Stray - это история о маленькой кошке, которая попадает в подземный город, полностью населенный роботами. Титулованному бродяге предстоит подружиться<p class="text-overflow"> с дроном, исследовать небольшие миры-концентраторы и решать головоломки с помощью своего кошачьего мозга, пытаясь вернуться домой</p><a class="dots">...</a>',
    newsSubTitle2: ` Игра будет бесплатной на высших уровнях PlayStation Plus. Stray, долгожданная приключенческая игра в стиле киберпанк, в которой<p class="text-overflow"> игрокам предстоит взять на себя роль кошки с рюкзаком, пробирающейся через кишащий роботами город, теперь имеет дату выхода. Первоначально игра планировалась к выпуску в "начале 2022 года", но официально она выйдет на PlayStation 5, PlayStation 4 и ПК 19 июля</p><a class="dots">...</a>`,
    newsSubTitle3: `Stray предоставит поклонникам возможность сыграть за цифровую версию идеальной мурлыкающей машины природы. В роли титулованного бродячего кота, потерявшегося в<p class="text-overflow"> странном городе, населенном роботами, вам предстоит помочь животному найти дорогу домой и избежать столкновения с безжалостными андроидами</p><a class="dots">...</a>`,
    question1: 'Когда состоится релиз??',
    question2: 'Игра дает возможность играть только за малекого кота?',
    question3: 'Что такое Stray?',
    answer1: `Релиз игры состоится 19 июля`,
    answer2: `Да, только за него .`,
    answer3:
      'История рассказывает о бродячей кошке, которая попадает в окруженный стенами город, населенный роботами, машинами и бактериями-мутантами, и пытается вернуться на поверхность с помощью дрона-компаньона B-12. Игра представлена с видом от третьего лица.',
    footerInfo:
      'Загрузка данного продукта регулируется Условиями обслуживания PlayStation Network и нашими Условиями использования программного обеспечения, а также любыми конкретными дополнительными условиями, применимыми к данному продукту. Если вы не хотите принимать эти условия, не загружайте этот продукт. Более подробную информацию см. в Условиях обслуживания.',
  },
}
